# Generated by Django 5.2.6 on 2025-09-05 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CiljStednje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=120)),
                ('cilj_iznos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('trenutno_stanje', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('datum_pocetka', models.DateField()),
                ('datum_kraja', models.DateField(blank=True, null=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('tip', models.CharField(choices=[('PRIHOD', 'Prihod'), ('TROSAK', 'Trošak')], max_length=10)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['naziv'],
                'unique_together': {('korisnik', 'naziv', 'tip')},
            },
        ),
        migrations.CreateModel(
            name='Transakcija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('datum', models.DateField()),
                ('opis', models.CharField(blank=True, max_length=255)),
                ('doprinos_cilju', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ciljstednje')),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.kategorija')),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datum', '-id'],
            },
        ),
    ]
