# Generated by Django 5.2.6 on 2025-09-13 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PonavljajucaTransakcija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('opis', models.CharField(max_length=255)),
                ('frekvencija', models.CharField(choices=[('DNEVNO', 'Dnevno'), ('TJEDNO', 'Tjedno'), ('MJESECNO', 'Mjesečno'), ('KVARTALNO', 'Kvartalno'), ('GODISNJE', 'Godišnje')], max_length=10)),
                ('datum_pocetka', models.DateField()),
                ('datum_kraja', models.DateField(blank=True, null=True)),
                ('aktivno', models.BooleanField(default=True)),
                ('sljedeci_datum', models.DateField()),
                ('doprinos_cilju', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ciljstednje')),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategorija')),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sljedeci_datum'],
            },
        ),
        migrations.AddField(
            model_name='transakcija',
            name='ponavljajuca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ponavljajucatransakcija'),
        ),
        migrations.CreateModel(
            name='Racun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('tip', models.CharField(choices=[('GOTOVINA', 'Gotovina'), ('BANKA', 'Banka'), ('KREDITNA', 'Kreditna kartica'), ('STEDNJA', 'Štednja'), ('OSTALO', 'Ostalo')], max_length=10)),
                ('pocetno_stanje', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('trenutno_stanje', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aktivno', models.BooleanField(default=True)),
                ('datum_kreiranja', models.DateTimeField(auto_now_add=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['naziv'],
                'unique_together': {('korisnik', 'naziv')},
            },
        ),
        migrations.AddField(
            model_name='transakcija',
            name='racun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.racun'),
        ),
        migrations.CreateModel(
            name='Budzet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period', models.CharField(choices=[('MJESEC', 'Mjesečni'), ('KVARTAL', 'Kvartalni'), ('GODINA', 'Godišnji')], default='MJESEC', max_length=10)),
                ('godina', models.IntegerField()),
                ('mjesec', models.IntegerField(blank=True, null=True)),
                ('aktivno', models.BooleanField(default=True)),
                ('datum_kreiranja', models.DateTimeField(auto_now_add=True)),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategorija')),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-godina', '-mjesec', 'kategorija__naziv'],
                'unique_together': {('korisnik', 'kategorija', 'godina', 'mjesec', 'period')},
            },
        ),
    ]
