# Generated by Django 5.2.6 on 2025-09-13 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ponavljajucatransakcija_transakcija_ponavljajuca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transakcija',
            name='racun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transakcije', to='core.racun'),
        ),
    ]
